theme: jekyll-theme-minimal
title: Arcadier Changelog
description: Major Changes in APIs documented here
logo: https://media-exp1.licdn.com/dms/image/C510BAQHqUlIUNTt84g/company-logo_200_200/0?e=2159024400&v=beta&t=oeoTTp8WNsuLcp67SYCsz4W6lhOuG9FN6ihDcyTVObY
